### PR TITLE
Pull Request. HUD changes, Bootstrap, Leaderboard, Sign In

### PR DESCRIPTION
**Pull request by nmaswood98**
Added more HUD, Modified the look of the menu with bootstrap, Separated HUD into own class. Added the leader board page which has a table from the given array supplied. Also the sign in username from aws now displays on the navbar when signed in

### CODE REVIEW

**Comment by RyanLinrm** [comment]
For the dragging functionality in HUD I think Hongejie is working on it too, he has finished the part where we can drag the unit out and than make it a enemy sprite object, I think he is working on the enemy finding attack target now, I will notify him that you have move the dragging to the HUD file, so he can just apply his modification on that file

**Comment by nmaswood98** [comment]
It should be very easy to move anything he added to HUD. Since before all the code was in the playscene I just moved it all into the constructor of the HUD class and replaced "this" with "scene"

**Comment by RyanLinrm** [comment]
great! thank you

**Comment by hongjiehuang** [comment]
I am working on a project that is due on wednesday, I will try to combine our HUD file together. I have finished basic enemy finding attack target stuff yesterday, I just had some problem with tower attacking enemy and I will try to solve it before the status meeting asap.

**Pull request merged**
