### PR TITLE
(Repull)Add JSDoc for enemy and units class, update single player playing style, fix mana/timer/hp errors, add enemy tests

### PR DESCRIPTION
**Pull request by hongjiehuang**
I have used JSDoc to add documentation for two classes, I will try to do more documentations on other classes if I have time. I added something to the single player, now it will be some kind of defending your tower from enemy waves, will update the design in the future. The enemy test is not yet finished, I will add more tests and testify them before the status meeting.

### CODE REVIEW

**Comment by hongjiehuang** [comment]
I have found some errors for the single player mode, I will fix it in my next pull, or you can just fix them while you merge.

**Comment by RyanLinrm** [comment]
What and where are the errors, if it will casue serious issue on the code in master repo, then I would suggest resend a pull request afterward, but if they are just some tiny issues that won't affect the actual game working I can fix them

**Comment by RyanLinrm** [comment]
you can just fix them and push it, I won't merge it now, I can wait for your fixing commit

**Comment by RyanLinrm** [comment]
Ok, I've received the newest commit, I'll merge them in after I go through the code, Thank you

**Pull request merged**
